language: python

python:
- '3.9'

install:
- pip install -r requirements.txt

addons:
  sonarcloud: true

script:
- sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=jowi20
  -Dsonar.login=$SONAR_TOKEN -X
- pytest

notifications:
  slack: entornodeinte-7kl4185:0528pUpzaLJ5FdQCjZ76JkBP


deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  keep_history: true
  on:
     repo: Jowi20/jowi20.github.io   
     branch: main
